# CSI 4107, Winter 2021
## Assignment 1 - Microblog information retrieval system

### Step 1: Preprocessing

In [1]:
import pandas as pd
import numpy as np
import math
import pandas_read_xml as pdx
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
from nltk.tokenize import RegexpTokenizer
from nltk.tokenize.treebank import TreebankWordDetokenizer
from collections import defaultdict
from collections import Counter
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import pairwise
from gensim.models import Doc2Vec
from gensim.models.doc2vec import TaggedDocument
from nltk import word_tokenize
import numpy

In [2]:
queriesDf = pdx.read_xml("../queries.xml", ['queries', 'top'])
queriesDf.head()

,num,title,querytime,querytweettime
0,Number: MB001,BBC World Service staff cuts,Tue Feb 08 12:30:27 +0000 2011,34952194402811904
1,Number: MB002,2022 FIFA soccer,Tue Feb 08 18:51:44 +0000 2011,35048150574039040
2,Number: MB003,Haiti Aristide return,Tue Feb 08 21:32:13 +0000 2011,35088534306033665
3,Number: MB004,Mexico drug war,Wed Feb 02 17:22:14 +0000 2011,32851298193768448
4,Number: MB005,NIST computer security,Fri Feb 04 17:44:09 +0000 2011,33581589627666432

In [3]:
#read tweets and transform into dataframe
data = []
with open('../Trec_microblog11.txt', 'r', encoding='utf-8', errors='replace') as infile:
    lines = infile.readlines()
    for i in lines:
        data.append(i.split('\t'))
        
data = np.array(data) #2d numpy array
        
df = pd.DataFrame({'ID': data[:, 0], 'text': data[:, 1]})
df.head()

                   ID                                               text
0  ﻿34952194402811904  Save BBC World Service from Savage Cuts http:/...
1   34952186328784896  a lot of people always make fun about the end ...
2   34952041415581696  ReThink Group positive in outlook: Technology ...
3   34952018120409088  'Zombie' fund manager Phoenix appoints new CEO...
4   34952008683229185  Latest:: Top World Releases http://globalclass...

In [4]:
stop = stopwords.words('english')

In [5]:
df['text_without_stopwords'] = df['text'].apply(lambda x: ' '.join([word for word in str(x).split() if word not in (stop)]))
df['text_without_stopwords'] = df['text_without_stopwords'].str.replace('\d+', '')
df['text_without_stopwords']=df['text_without_stopwords'].apply(str.lower)

queriesDf['text_without_stopwords'] = queriesDf['title'].apply(lambda x: ' '.join([word for word in str(x).split() if word not in (stop)]))
queriesDf['text_without_stopwords'] = queriesDf['text_without_stopwords'].str.replace('\d+', '')
queriesDf['text_without_stopwords'] = queriesDf['text_without_stopwords'].apply(str.lower)

<ipython-input-5-d442573762f1>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df['text_without_stopwords'] = df['text_without_stopwords'].str.replace('\d+', '')
<ipython-input-5-d442573762f1>:6: FutureWarning: The default value of regex will change from True to False in a future version.
  queriesDf['text_without_stopwords'] = queriesDf['text_without_stopwords'].str.replace('\d+', '')

In [6]:
queriesDf['topic_id'] = queriesDf['num'].apply(lambda x : x.split(' '))
queriesDf['topic_id'] = queriesDf['topic_id'].apply(lambda x: x[1])

In [7]:
tokenizer = RegexpTokenizer(r'\w+')
pstemmer = PorterStemmer()

#tokenize and stem a string
#not used cuz got worse results with stemmed words
def tokenizer_stemmer(str):
    tokens = tokenizer.tokenize(str)
    for i in range(len(tokens)):
        tokens[i] = pstemmer.stem(tokens[i])
    return tokens

#tokenize dataframes
df['token'] = df['text_without_stopwords'].apply(lambda x: tokenizer.tokenize(x))
queriesDf['token'] = queriesDf['text_without_stopwords'].apply(lambda x: tokenizer.tokenize(x))

In [8]:
# detokenize for easier query/document vectorization
df['detoken']=df['token'].apply(lambda x: TreebankWordDetokenizer().detokenize(x))
queriesDf['detoken']=queriesDf['token'].apply(lambda x: TreebankWordDetokenizer().detokenize(x))

In [9]:
queriesDf.head()

,num,title,querytime,querytweettime,text_without_stopwords,topic_id,token,detoken
0,Number: MB001,BBC World Service staff cuts,Tue Feb 08 12:30:27 +0000 2011,34952194402811904,bbc world service staff cuts,MB001,"[bbc, world, service, staff, cuts]",bbc world service staff cuts
1,Number: MB002,2022 FIFA soccer,Tue Feb 08 18:51:44 +0000 2011,35048150574039040,fifa soccer,MB002,"[fifa, soccer]",fifa soccer
2,Number: MB003,Haiti Aristide return,Tue Feb 08 21:32:13 +0000 2011,35088534306033665,haiti aristide return,MB003,"[haiti, aristide, return]",haiti aristide return
3,Number: MB004,Mexico drug war,Wed Feb 02 17:22:14 +0000 2011,32851298193768448,mexico drug war,MB004,"[mexico, drug, war]",mexico drug war
4,Number: MB005,NIST computer security,Fri Feb 04 17:44:09 +0000 2011,33581589627666432,nist computer security,MB005,"[nist, computer, security]",nist computer security

In [10]:
df.head()

,ID,text,text_without_stopwords,token,detoken
0,﻿34952194402811904,Save BBC World Service from Savage Cuts http:/...,save bbc world service savage cuts http://www....,"[save, bbc, world, service, savage, cuts, http...",save bbc world service savage cuts http www pe...
1,34952186328784896,a lot of people always make fun about the end ...,lot people always make fun end world question ...,"[lot, people, always, make, fun, end, world, q...",lot people always make fun end world question ...
2,34952041415581696,ReThink Group positive in outlook: Technology ...,rethink group positive outlook: technology sta...,"[rethink, group, positive, outlook, technology...",rethink group positive outlook technology staf...
3,34952018120409088,'Zombie' fund manager Phoenix appoints new CEO...,'zombie' fund manager phoenix appoints new ceo...,"[zombie, fund, manager, phoenix, appoints, new...",zombie fund manager phoenix appoints new ceo p...
4,34952008683229185,Latest:: Top World Releases http://globalclass...,latest:: top world releases http://globalclass...,"[latest, top, world, releases, http, globalcla...",latest top world releases http globalclassifie...

In [11]:

#df['token'][26]#test to see if numbers have been removed
#print(df['token'][12898])

### Step 2: Indexing

In [12]:


# key [doc]
# reverse index
def create_index (data):
        index = defaultdict(list)
        count=0
        for i, tokens in enumerate(data):
            for token in tokens:
                index[token].append(i)
                #index[save].append(doc)
        return index



def count_occurrences(arr):
    return list(Counter(arr).items())



# key, [(doc#, count)]
def final_index(index):
    final=defaultdict(list)
    for key in index.keys():
        final[key] = count_occurrences(index[key])
    return final

# each token (save, bbc) as your dict key
# append the count_occurrences based on index
#final_index creates the final hash table for inverted index. {word: [(doc#, number of occurrences in that document)]}
# doc# in this case is the line number of the table, not the message ID.

In [13]:
test=create_index(df['token'])
test2=count_occurrences([0, 1, 44, 44, 443])
rev_index=final_index(test)

#print(len(rev_index.keys()))

In [14]:
print(list(rev_index.keys())[0:100]) # get a sample of 100 tokens from vocab

['save', 'bbc', 'world', 'service', 'savage', 'cuts', 'http', 'www', 'petitionbuzz', 'com', 'petitions', 'savews', 'lot', 'people', 'always', 'make', 'fun', 'end', 'question', 'is', 'are', 'u', 'ready', 'for', 'it', 'rethink', 'group', 'positive', 'outlook', 'technology', 'staffing', 'specialist', 'expects', 'revenues', 'marg', 'bit', 'ly', 'hfjtmy', 'zombie', 'fund', 'manager', 'phoenix', 'appoints', 'new', 'ceo', 'buys', 'funds', 'closed', 'business', 'dxrlh', 'latest', 'top', 'releases', 'globalclassified', 'net', 'cdt', 'presents', 'alice', 'in', 'wonderland', 'catonsville', 'dinner', 'posted', 'the', 'fb', 'me', 'gmicayt', 'territory', 'location', 'calgary', 'alberta', 'canada', 'job', 'category', 'bu', 'eomt', 'jobs', 'news', 'today', 'free', 'school', 'funding', 'plans', 'lack', 'transparency', 'co', 'uk', 'hi', 'newsid_', 'stm', 'manchester', 'city', 'council', 'details', 'saving', 'plan', 'fypypc', 'depressing', 'apparently', 'we']

## Step 3: Retrieval and Ranking

In [15]:
# query: list of tokens for a query
# docs: inverted hash index with key:value of token:[(doc_num,num_occurances,...)]
def related_documents_to_query(query, docs):
    related_docs = []
    for token in query:
        if token in docs:
            related_docs+=docs[token]

    nums_only = []
    for x in related_docs:
        nums_only.append(x[0])

    return set(nums_only)


#get vocabulary
vocab= []
for arr in df['token']:
    vocab += arr
vocab = set(vocab)

#create td-idf matrix
corpus = df['detoken']
docVectorizer = TfidfVectorizer(vocabulary = vocab, sublinear_tf=True)
docMatrix = docVectorizer.fit_transform(corpus)
docVocabulary = docVectorizer.vocabulary_
#docMatrix.toarray()


#find cosine similarity
#returns an array of (doc_num, similarity) tuples
def similarity_cosine(query_vector, docs):
    sim_arr = []
    
    for doc in docs: 
        similarity = pairwise.cosine_similarity(doc[1], query_vector)
        sim_arr.append((doc[0], similarity[0][0]))
    return sim_arr 


print(len(docVocabulary))

87685

In [16]:

# final results: array of length # of queries with tuples of (query, top_1000_docs)
# where top_1000_docs is an array of tuples of (doc_num, similarity)
final_results = []

for index, q_row in queriesDf.iterrows():
    # for each query, get set of related docs (doc #, num of occurences)
    related_docs = related_documents_to_query(q_row['token'], rev_index)
    
    related_docs_matrix = []
    #get vectors of related docs
    for doc_num in related_docs:
        related_docs_matrix.append((doc_num, docMatrix[doc_num]) )

    # get similarities
    qvec = docVectorizer.transform([q_row['detoken']]) # vectorize query
        
    sim_arr = similarity_cosine(qvec, related_docs_matrix)
    
    #sort by similarity
    ranked = sorted(sim_arr, key = lambda x : x[1], reverse = True)
    
    # rank top 1000
    top_1000 = ranked[0:1000]
    
    # add to final results array
    final_results.append( (q_row['num'], top_1000) )

In [17]:
docresults=[] #1d list of doc nums only
doc_results_w_num = [] #list of lists containing docnums for each query result
for i in range(len(final_results)):
    doc_results_w_num.append([])
    for j in range(len(final_results[i][1])): #array of 1000 docs in tuples (doc_row, similarity)
        docno = df['ID'][final_results[i][1][j][0]]
        docresults.append(docno)
        doc_results_w_num[i].append(docno)

In [29]:
#using sent2vec code from https://pypi.org/project/sent2vec/
from sent2vec.vectorizer import Vectorizer

vectorizer = Vectorizer()

vectorizer.bert(queriesDf['detoken'])
vectors_tmp = vectorizer.vectors

print(vectors_tmp.shape)

(49, 768)

In [34]:
# convert queries to vectors and write to file
query_vecs_file = open("query_vecs.txt", "w+", encoding="utf-8") 
query_vecs_file.write("\n".join(" ".join(map(str, x)) for x in vectors_tmp))
query_vecs_file.close()

In [40]:
# RUN ONLY ONCE, takes a long time
# convert each document to a vector and write to file, do in batches of 25 docs to avoid using too much RAM
docs_vecs_file = open("doc_vecs.txt", "w+", encoding="utf-8") 
for i in range(0, len(df['detoken']), 25): #process all docs in  batches of 50
    vectors_tmp = []
    print(i)
    vectorizer.bert(df['detoken'][i:i+25])
    vectors_tmp = vectorizer.vectors
    #print(vectors_tmp.shape)
    docs_vecs_file.write("\n".join(" ".join(map(str, x)) for x in vectors_tmp))
    docs_vecs_file.write("\n")
docs_vecs_file.close()

0
25
50
75
100
125
150
175
200
225
250
275
300
325
350
375
400
425
450
475
500
525
550
575
600
625
650
675
700
725
750
775
800
825
850
875
900
925
950
975
1000
1025
1050
1075
1100
1125
1150
1175
1200
1225
1250
1275
1300
1325
1350
1375
1400
1425
1450
1475
1500
1525
1550
1575
1600
1625
1650
1675
1700
1725
1750
1775
1800
1825
1850
1875
1900
1925
1950
1975
2000
2025
2050
2075
2100
2125
2150
2175
2200
2225
2250
2275
2300
2325
2350
2375
2400
2425
2450
2475
2500
2525
2550
2575
2600
2625
2650
2675
2700
2725
2750
2775
2800
2825
2850
2875
2900
2925
2950
2975
3000
3025
3050
3075
3100
3125
3150
3175
3200
3225
3250
3275
3300
3325
3350
3375
3400
3425
3450
3475
3500
3525
3550
3575
3600
3625
3650
3675
3700
3725
3750
3775
3800
3825
3850
3875
3900
3925
3950
3975
4000
4025
4050
4075
4100
4125
4150
4175
4200
4225
4250
4275
4300
4325
4350
4375
4400
4425
4450
4475
4500
4525
4550
4575
4600
4625
4650
4675
4700
4725
4750
4775
4800
4825
4850
4875
4900
4925
4950
4975
5000
5025
5050
5075
5100
5125
5150
5175
5200
5225
5250
5275
5300
5325
5350
5375
5400
5425
5450
5475
5500
5525
5550
5575
5600
5625
5650
5675
5700
5725
5750
5775
5800
5825
5850
5875
5900
5925
5950
5975
6000
6025
6050
6075
6100
6125
6150
6175
6200
6225
6250
6275
6300
6325
6350
6375
6400
6425
6450
6475
6500
6525
6550
6575
6600
6625
6650
6675
6700
6725
6750
6775
6800
6825
6850
6875
6900
6925
6950
6975
7000
7025
7050
7075
7100
7125
7150
7175
7200
7225
7250
7275
7300
7325
7350
7375
7400
7425
7450
7475
7500
7525
7550
7575
7600
7625
7650
7675
7700
7725
7750
7775
7800
7825
7850
7875
7900
7925
7950
7975
8000
8025
8050
8075
8100
8125
8150
8175
8200
8225
8250
8275
8300
8325
8350
8375
8400
8425
8450
8475
8500
8525
8550
8575
8600
8625
8650
8675
8700
8725
8750
8775
8800
8825
8850
8875
8900
8925
8950
8975
9000
9025
9050
9075
9100
9125
9150
9175
9200
9225
9250
9275
9300
9325
9350
9375
9400
9425
9450
9475
9500
9525
9550
9575
9600
9625
9650
9675
9700
9725
9750
9775
9800
9825
9850
9875
9900
9925
9950
9975
10000
10025
10050
10075
10100
10125
10150
10175
10200
10225
10250
10275
10300
10325
10350
10375
10400
10425
10450
10475
10500
10525
10550
10575
10600
10625
10650
10675
10700
10725
10750
10775
10800
10825
10850
10875
10900
10925
10950
10975
11000
11025
11050
11075
11100
11125
11150
11175
11200
11225
11250
11275
11300
11325
11350
11375
11400
11425
11450
11475
11500
11525
11550
11575
11600
11625
11650
11675
11700
11725
11750
11775
11800
11825
11850
11875
11900
11925
11950
11975
12000
12025
12050
12075
12100
12125
12150
12175
12200
12225
12250
12275
12300
12325
12350
12375
12400
12425
12450
12475
12500
12525
12550
12575
12600
12625
12650
12675
12700
12725
12750
12775
12800
12825
12850
12875
12900
12925
12950
12975
13000
13025
13050
13075
13100
13125
13150
13175
13200
13225
13250
13275
13300
13325
13350
13375
13400
13425
13450
13475
13500
13525
13550
13575
13600
13625
13650
13675
13700
13725
13750
13775
13800
13825
13850
13875
13900
13925
13950
13975
14000
14025
14050
14075
14100
14125
14150
14175
14200
14225
14250
14275
14300
14325
14350
14375
14400
14425
14450
14475
14500
14525
14550
14575
14600
14625
14650
14675
14700
14725
14750
14775
14800
14825
14850
14875
14900
14925
14950
14975
15000
15025
15050
15075
15100
15125
15150
15175
15200
15225
15250
15275
15300
15325
15350
15375
15400
15425
15450
15475
15500
15525
15550
15575
15600
15625
15650
15675
15700
15725
15750
15775
15800
15825
15850
15875
15900
15925
15950
15975
16000
16025
16050
16075
16100
16125
16150
16175
16200
16225
16250
16275
16300
16325
16350
16375
16400
16425
16450
16475
16500
16525
16550
16575
16600
16625
16650
16675
16700
16725
16750
16775
16800
16825
16850
16875
16900
16925
16950
16975
17000
17025
17050
17075
17100
17125
17150
17175
17200
17225
17250
17275
17300
17325
17350
17375
17400
17425
17450
17475
17500
17525
17550
17575
17600
17625
17650
17675
17700
17725
17750
17775
17800
17825
17850
17875
17900
17925
17950
17975
18000
18025
18050
18075
18100
18125
18150
18175
18200
18225
18250
18275
18300
18325
18350
18375
18400
18425
18450
18475
18500
18525
18550
18575
18600
18625
18650
18675
18700
18725
18750
18775
18800
18825
18850
18875
18900
18925
18950
18975
19000
19025
19050
19075
19100
19125
19150
19175
19200
19225
19250
19275
19300
19325
19350
19375
19400
19425
19450
19475
19500
19525
19550
19575
19600
19625
19650
19675
19700
19725
19750
19775
19800
19825
19850
19875
19900
19925
19950
19975
20000
20025
20050
20075
20100
20125
20150
20175
20200
20225
20250
20275
20300
20325
20350
20375
20400
20425
20450
20475
20500
20525
20550
20575
20600
20625
20650
20675
20700
20725
20750
20775
20800
20825
20850
20875
20900
20925
20950
20975
21000
21025
21050
21075
21100
21125
21150
21175
21200
21225
21250
21275
21300
21325
21350
21375
21400
21425
21450
21475
21500
21525
21550
21575
21600
21625
21650
21675
21700
21725
21750
21775
21800
21825
21850
21875
21900
21925
21950
21975
22000
22025
22050
22075
22100
22125
22150
22175
22200
22225
22250
22275
22300
22325
22350
22375
22400
22425
22450
22475
22500
22525
22550
22575
22600
22625
22650
22675
22700
22725
22750
22775
22800
22825
22850
22875
22900
22925
22950
22975
23000
23025
23050
23075
23100
23125
23150
23175
23200
23225
23250
23275
23300
23325
23350
23375
23400
23425
23450
23475
23500
23525
23550
23575
23600
23625
23650
23675
23700
23725
23750
23775
23800
23825
23850
23875
23900
23925
23950
23975
24000
24025
24050
24075
24100
24125
24150
24175
24200
24225
24250
24275
24300
24325
24350
24375
24400
24425
24450
24475
24500
24525
24550
24575
24600
24625
24650
24675
24700
24725
24750
24775
24800
24825
24850
24875
24900
24925
24950
24975
25000
25025
25050
25075
25100
25125
25150
25175
25200
25225
25250
25275
25300
25325
25350
25375
25400
25425
25450
25475
25500
25525
25550
25575
25600
25625
25650
25675
25700
25725
25750
25775
25800
25825
25850
25875
25900
25925
25950
25975
26000
26025
26050
26075
26100
26125
26150
26175
26200
26225
26250
26275
26300
26325
26350
26375
26400
26425
26450
26475
26500
26525
26550
26575
26600
26625
26650
26675
26700
26725
26750
26775
26800
26825
26850
26875
26900
26925
26950
26975
27000
27025
27050
27075
27100
27125
27150
27175
27200
27225
27250
27275
27300
27325
27350
27375
27400
27425
27450
27475
27500
27525
27550
27575
27600
27625
27650
27675
27700
27725
27750
27775
27800
27825
27850
27875
27900
27925
27950
27975
28000
28025
28050
28075
28100
28125
28150
28175
28200
28225
28250
28275
28300
28325
28350
28375
28400
28425
28450
28475
28500
28525
28550
28575
28600
28625
28650
28675
28700
28725
28750
28775
28800
28825
28850
28875
28900
28925
28950
28975
29000
29025
29050
29075
29100
29125
29150
29175
29200
29225
29250
29275
29300
29325
29350
29375
29400
29425
29450
29475
29500
29525
29550
29575
29600
29625
29650
29675
29700
29725
29750
29775
29800
29825
29850
29875
29900
29925
29950
29975
30000
30025
30050
30075
30100
30125
30150
30175
30200
30225
30250
30275
30300
30325
30350
30375
30400
30425
30450
30475
30500
30525
30550
30575
30600
30625
30650
30675
30700
30725
30750
30775
30800
30825
30850
30875
30900
30925
30950
30975
31000
31025
31050
31075
31100
31125
31150
31175
31200
31225
31250
31275
31300
31325
31350
31375
31400
31425
31450
31475
31500
31525
31550
31575
31600
31625
31650
31675
31700
31725
31750
31775
31800
31825
31850
31875
31900
31925
31950
31975
32000
32025
32050
32075
32100
32125
32150
32175
32200
32225
32250
32275
32300
32325
32350
32375
32400
32425
32450
32475
32500
32525
32550
32575
32600
32625
32650
32675
32700
32725
32750
32775
32800
32825
32850
32875
32900
32925
32950
32975
33000
33025
33050
33075
33100
33125
33150
33175
33200
33225
33250
33275
33300
33325
33350
33375
33400
33425
33450
33475
33500
33525
33550
33575
33600
33625
33650
33675
33700
33725
33750
33775
33800
33825
33850
33875
33900
33925
33950
33975
34000
34025
34050
34075
34100
34125
34150
34175
34200
34225
34250
34275
34300
34325
34350
34375
34400
34425
34450
34475
34500
34525
34550
34575
34600
34625
34650
34675
34700
34725
34750
34775
34800
34825
34850
34875
34900
34925
34950
34975
35000
35025
35050
35075
35100
35125
35150
35175
35200
35225
35250
35275
35300
35325
35350
35375
35400
35425
35450
35475
35500
35525
35550
35575
35600
35625
35650
35675
35700
35725
35750
35775
35800
35825
35850
35875
35900
35925
35950
35975

36000
36025
36050
36075
36100
36125
36150
36175
36200
36225
36250
36275
36300
36325
36350
36375
36400
36425
36450
36475
36500
36525
36550
36575
36600
36625
36650
36675
36700
36725
36750
36775
36800
36825
36850
36875
36900
36925
36950
36975
37000
37025
37050
37075
37100
37125
37150
37175
37200
37225
37250
37275
37300
37325
37350
37375
37400
37425
37450
37475
37500
37525
37550
37575
37600
37625
37650
37675
37700
37725
37750
37775
37800
37825
37850
37875
37900
37925
37950
37975
38000
38025
38050
38075
38100
38125
38150
38175
38200
38225
38250
38275
38300
38325
38350
38375
38400
38425
38450
38475
38500
38525
38550
38575
38600
38625
38650
38675
38700
38725
38750
38775
38800
38825
38850
38875
38900
38925
38950
38975
39000
39025
39050
39075
39100
39125
39150
39175
39200
39225
39250
39275
39300
39325
39350
39375
39400
39425
39450
39475
39500
39525
39550
39575
39600
39625
39650
39675
39700
39725
39750
39775
39800
39825
39850
39875
39900
39925
39950
39975
40000
40025
40050
40075
40100
40125
40150
40175
40200
40225
40250
40275
40300
40325
40350
40375
40400
40425
40450
40475
40500
40525
40550
40575
40600
40625
40650
40675
40700
40725
40750
40775
40800
40825
40850
40875
40900
40925
40950
40975
41000
41025
41050
41075
41100
41125
41150
41175
41200
41225
41250
41275
41300
41325
41350
41375
41400
41425
41450
41475
41500
41525
41550
41575
41600
41625
41650
41675
41700
41725
41750
41775
41800
41825
41850
41875
41900
41925
41950
41975
42000
42025
42050
42075
42100
42125
42150
42175
42200
42225
42250
42275
42300
42325
42350
42375
42400
42425
42450
42475
42500
42525
42550
42575
42600
42625
42650
42675
42700
42725
42750
42775
42800
42825
42850
42875
42900
42925
42950
42975
43000
43025
43050
43075
43100
43125
43150
43175
43200
43225
43250
43275
43300
43325
43350
43375
43400
43425
43450
43475
43500
43525
43550
43575
43600
43625
43650
43675
43700
43725
43750
43775
43800
43825
43850
43875
43900
43925
43950
43975
44000
44025
44050
44075
44100
44125
44150
44175
44200
44225
44250
44275
44300
44325
44350
44375
44400
44425
44450
44475
44500
44525
44550
44575
44600
44625
44650
44675
44700
44725
44750
44775
44800
44825
44850
44875
44900
44925
44950
44975
45000
45025
45050
45075
45100
45125
45150
45175
45200
45225
45250
45275
45300
45325
45350
45375
45400
45425
45450
45475
45500
45525
45550
45575
45600
45625
45650
45675
45700
45725
45750
45775
45800
45825
45850
45875

In [42]:
#converts a str line of decimals, seperated by spaces, to array of decimals
def str_to_vec(line):
    line = line.rstrip().split(" ")
    return [float(x) for x in line]

# read query vectors from file
query_vectors = []
with open("query_vecs.txt", "r", encoding="utf-8") as f:
    query_vectors = [str_to_vec(line) for line in f]

# read doc vectors from file
doc_vectors = []
with open("doc_vecs.txt", "r", encoding="utf-8") as f:
    doc_vectors = [str_to_vec(line) for line in f]


#print(query_vectors[0])
print(len(query_vectors))
print(len(doc_vectors))

49
45899

In [55]:
final_results2 = []

for index, q_row in queriesDf.iterrows():
    # for each query, get top_1000 docs previously retreived
    related_docs =  doc_results_w_num[index]
    related_docs_matrix = []
    
    #get vectors of related docs
    for doc_num in related_docs:
        # get vector of each doc using new model
        #related_docs_tokens = related_docs_tokens.append((df.loc[df['ID']==doc_num]['detoken']).item())
        doc_index =  df.loc[df['ID']==doc_num]['detoken'].index
        doc_vec = doc_vectors[doc_index[0]]
        related_docs_matrix.append((doc_num, [doc_vec]))  
            
    # get query vector
    qvec = query_vectors[index]
    sim_arr = similarity_cosine([qvec], related_docs_matrix)
    
    #sort by similarity
    ranked = sorted(sim_arr, key = lambda x : x[1], reverse = True)
    
    # add to final results array
    final_results2.append( (q_row['num'], ranked) )

## Step 4: Write to file

In [53]:
# sample line: topic_id Q0 docno rank score tag
# topic_id: queriesDf['topic_id'][i]
# docno: df['ID'][resultsMatrix[i][j][0]]
# rank: j from resultsMatrix[i], +1 because highest rank is 1 not 0
# score: resultsMatrix[i][j][1]
# tag: passed in at function call

def write_results(tag, resultMatrix):
    
    f = open("results.txt", "w+", encoding="utf-8")
    
    for i in range(len(resultMatrix)):
        topic_id = queriesDf['topic_id'][i][2:].lstrip('0') #[2:].lstrip('0') to strip "MB" and leading 0s to end up with plain number

        for j in range(len(resultMatrix[i][1])): #array of 1000 docs in tuples (doc_row, similarity)
            
            docno = resultMatrix[i][1][j][0]
            rank = j +1
            score = resultMatrix[i][1][j][1]
            new_line = topic_id + " Q0 " + str(docno) + " " + str(rank) + " " + str(score) + " " + tag + "\n"
            f.write(new_line)
        
    f.close()

In [54]:
write_results('STANDARD',final_results2)
print('done')

done